### PR TITLE
resizewidget - test and documentation

### PR DESCRIPTION
**Pull request by wernerfb**

### CODE REVIEW

**Comment by Metallicow** [comment]
I see a few more improvements that could be made.

1. The event handler docstr's should be consistent with the andreas/agw style; These provide the hyperlinking needed to easily navigate the output documentation.
 Ex:
 ```
         """
         Handles the ``wx.EVT_SIZE`` event for :class:`MyClassName`.

         :param `event`: A `wx.SizeEvent` to be processed.
         """
 ```

2. "evt" arg spelling should be changed in these methods to "event" for readability. evt in a demo or derived code is ok, but the library resource should be as readable as possible.

**Comment by Metallicow** [comment]
@wernerfb I actually meant in the lib module code that 'event' not 'evt' should be the primary.
So, the other way around.

This may seem minimal to those of us that are already familiar with python and wxpython, but was always an irritation when I was first learning as instances of this would confuse me a bit. 'evt' is alphabet soup as 'event' is readable and has some more meaning. And chances are that newcomers to wxpython/phoenix will notice these small inconsistancies in the lib code(which also shows in the docs).

Sorry if that was misunderstood. 
Ex: just swaping(replacing) all instances of 'evt' with 'event' was what I intended.

I believe the usage of 'evt' and 'e' and 'etc'... originally showed up in the demos often because it is shorter for example and this unreadability was passed on into the lib code unintentionally by habit.

**Comment by wernerfb** [comment]
@Metallicow I know that you wanted to see 'event' and not 'evt', but just didn't have time to do code changes and test them, but wanted to get the docu stuff done.

**Comment by Metallicow** [comment]
Thanks for the doc efforts. I understand time constraints.
I have plenty of things myself I work on besides small details at times, but is worth noting as someone else may pass this by and continue working on readability. As I have said before, I am not much of a documentarist, but live by the docs. Everyone involved appreciates the work put into it, so thanks again.
Maybe after a formal first RELz we or others can focus more on readability, whitespace, etc changes...

**Comment by RobinD42** [comment]
I tend to prefer evt, which is why I merged the PR without that change.  I think that most programmers would be able to guess that "evt" means "event" in the context of an event handler function.

**Comment by Metallicow** [comment]
@RobinD42 This reminds me of who showed me the different ways of looking at code and while is a great programmer, explained to me on a sheet of paper exactly what I had taught him the same way a different day in a bit different language verbally and hand-written but in code. Basically what we talked about that night was variables and that anything could be anything and that interpretation was up to the user not the coder. I was left with a piece of code like this that taught me a bit personally about how programmers think. So I was recommended a ref book for my language.

```
def grok(grok):
    import this
    return this.s
```

I found it a bit amusing that language being used at the time was the variable after some deep thought. Being a bit of a reader, I was recommended to start with python as you can easily guess.

**Pull request merged**
