### PR TITLE
pdfviewer - Py3.4 support

### PR DESCRIPTION
**Pull request by wernerfb**
Still work in progress!!
On Py3.4 I get some unittest failures
On Py2.7 sample.pdf displays correctly, on Py3.4 I get an exception which I reported to PyPDF2.
Files with images have problems, i.e. do not display correctly

### CODE REVIEW

**Comment by wernerfb** [comment]
There is a PR for PyPDF2 which helps, i.e. fixes the exception but the sample.pdf does still not display correctly on Py3.4.
https://github.com/mstamy2/PyPDF2/pull/172

**Comment by RobinD42** [comment]
Closing really old PRs...

If this is still relevant and needed please recreate it based on the current master branch, and send to the wxWidgets/Phoenix github project.

**Comment by wernerfb** [comment]
Hi Robin,
I believe this is still relevant, but I will not have the time to redo it against latest master for a long time.  Hopefully someone else who is using pdfviewer will pick it up.

**Comment by RobinD42** [comment]
Moved to https://github.com/wxWidgets/Phoenix/pull/40

**Pull request closed without merging**
